// File: pages/terms.js (Final Version)
import StandardLayout from '../components/layout/StandardLayout';
import Link from 'next/link';
import Head from 'next/head';

export default function TermsPage() {
  
  const Section = ({ title, children }) => (
    <section className="legal-section">
      <h2 className="section-heading">{title}</h2>
      <div className="section-content">{children}</div>
    </section>
  );

  return (
    <StandardLayout
      pageType="standard"
      title="Terms of Service - GriotBot"
      description="Read the Terms of Service for using the GriotBot platform."
      currentPath="/terms"
    >
      <Head>
        {/* Additional specific head elements if needed */}
      </Head>
      <article className="legal-container">
        <header className="legal-header">
          <h1>Terms of Service</h1>
          <p>Last Updated: June 22, 2025</p>
        </header>
        
        <p className="intro">
          Welcome to GriotBot. These Terms of Service ("Terms") govern your use of the GriotBot website and its related services (collectively, the "Service"), provided by GriotBot Corporation ("we," "us," or "our"). By accessing or using our Service, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use the Service. Your use of the Service is also subject to our{' '}
          <Link href="/privacy" legacyBehavior>
            <a className="inline-link">Privacy Policy</a>
          </Link>
          , which explains how we collect, use, and protect your personal information.
        </p>

        <Section title="1. Use of the Service">
            <ul className="styled-list">
                <li><strong>Eligibility:</strong> You must be at least 13 years old to use the Service.</li>
                <li><strong>Permitted Use:</strong> You agree to use the Service only for lawful purposes and in a way that does not infringe the rights of, restrict, or inhibit anyone else's use and enjoyment of the Service.</li>
                <li><strong>Prohibited Use:</strong> You may not use the Service to generate content that is hateful, harassing, violent, or that violates any applicable laws or the rights of any third party. You further agree not to use the Service to:
                    <ul>
                        <li>Generate or disseminate false or misleading information.</li>
                        <li>Promote hate speech, racism, or cultural appropriation.</li>
                        <li>Attempt to bypass safety features or manipulate responses.</li>
                        <li>Engage in automated or bot-driven scraping or abuse of the Service.</li>
                    </ul>
                </li>
            </ul>
        </Section>
        
        <Section title="2. Service Content and AI-Generated Content">
            <ul className="styled-list">
                <li><strong>Nature of Content:</strong> The content provided by GriotBot is generated by an artificial intelligence model. While we strive for cultural accuracy and authenticity, the responses are generated by a machine and may contain inaccuracies or omissions.</li>
                <li><strong>No Professional Advice:</strong> The content provided by GriotBot is for informational and entertainment purposes only. It does not constitute and should not be relied upon as legal, financial, medical, or other professional advice. Always consult with a qualified professional for your specific situation.</li>
                <li><strong>Ownership of Generated Content:</strong> You may use the content generated for you by the Service (the "Output") for personal, educational, or non-commercial purposes. For any commercial use (e.g., publishing, resale), please contact us at <strong>chat@griotbot.com</strong>.</li>
            </ul>
        </Section>

        <Section title="3. User Conduct and Responsibilities">
             <ul className="styled-list">
                <li><strong>Your Inputs:</strong> You are responsible for your use of the Service and for any prompts, messages, or other content you provide ("Inputs").</li>
                <li><strong>License to Use Inputs:</strong> By submitting Inputs to the Service, you grant GriotBot Corporation a non-exclusive, royalty-free, worldwide license to use that content to provide and improve the Service.</li>
                <li><strong>Sensitive Information:</strong> Do not submit any content you do not have the right to share or that contains personally identifiable or sensitive information about yourself or others.</li>
            </ul>
        </Section>

        <Section title="4. Disclaimers and Limitation of Liability">
            <p>THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WE MAKE NO WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, RELIABILITY, OR COMPLETENESS OF THE SERVICE OR ITS CONTENT.</p>
            <p>TO THE FULLEST EXTENT PERMITTED BY LAW, GRIOTBOT CORPORATION SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, RESULTING FROM YOUR ACCESS TO OR USE OF THE SERVICE.</p>
        </Section>

        <Section title="5. Changes to Terms">
            <p>We reserve the right to modify these Terms at any time. We will provide notice of any significant changes. Your continued use of the Service after such changes constitutes your acceptance of the new Terms.</p>
        </Section>

        <Section title="6. Governing Law">
            <p>These Terms shall be governed by and construed in accordance with the laws of the <strong>State of Maryland, United States</strong>, without regard to its conflict of law principles.</p>
        </Section>

        <Section title="7. Termination">
            <p>We reserve the right to suspend or terminate your access to the Service at our sole discretion, without notice, for behavior that violates these Terms or is otherwise harmful to the community or platform.</p>
        </Section>

        <Section title="8. Contact Us">
            <p>If you have any questions about these Terms, please contact us at <a href="mailto:chat@griotbot.com" className="inline-link">chat@griotbot.com</a>.</p>
        </Section>

      </article>

      <style jsx>{`
        .legal-container {
          max-width: 800px;
          margin: 2rem auto 4rem auto;
          padding: 0 1rem;
          line-height: 1.8;
          font-size: 1rem;
        }
        .legal-header {
          text-align: center;
          margin-bottom: 3rem;
          padding-bottom: 1rem;
          border-bottom: 1px solid var(--input-border);
        }
        .legal-header h1 {
          font-family: var(--heading-font);
          font-size: 2.5rem;
          margin-bottom: 0.5rem;
        }
        .legal-header p, .intro {
          color: var(--text-color);
          opacity: 0.8;
        }
        .intro {
            margin-bottom: 2rem;
        }
        .legal-section {
          margin-bottom: 2.5rem;
        }
        .section-heading {
          font-family: var(--heading-font);
          font-size: 1.5rem;
          color: var(--accent-color);
          margin-bottom: 1rem;
        }
        .section-content {
          padding-left: 1rem;
          border-left: 3px solid var(--input-border);
        }
        .styled-list {
          padding-left: 20px;
          list-style: none;
        }
        .styled-list li {
          position: relative;
          padding-left: 25px;
          margin-bottom: 1rem;
        }
        .styled-list li::before {
          content: '▸';
          position: absolute;
          left: 0;
          color: var(--accent-color);
          font-weight: bold;
        }
        .inline-link {
            color: var(--accent-color);
            font-weight: 500;
            text-decoration: none;
        }
        .inline-link:hover {
            text-decoration: underline;
        }
      `}</style>
    </StandardLayout>
  );
}
